services:
  winloss-tracker:
    build: .
    container_name: winloss_tracker
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./public/defaults:/app/public/defaults
    env_file:
      - .env
    environment:
      - NODE_ENV=production
