-- =========================================================================
-- 💡 熱修復指引 (如果您已經建立過表格，請直接在 Supabase SQL Editor 執行以下這段熱修復指令即可)：
-- -- 先刪除依賴 user_id 欄位的原有 RLS 政策，避免出現 0A000 cannot alter type of a column used in a policy definition 錯誤
-- DROP POLICY IF EXISTS "Allow read access to owner or guests" ON public.winloss_records;
-- DROP POLICY IF EXISTS "Allow insert access to anyone" ON public.winloss_records;
-- DROP POLICY IF EXISTS "Allow delete access to owners or guests" ON public.winloss_records;
-- 
-- -- 接著安全地將 user_id 改成 text 類型
-- ALTER TABLE public.winloss_records ALTER COLUMN user_id TYPE text USING user_id::text;
-- 
-- -- 最後重新建立並套用正確型態轉換的比對政策
-- CREATE POLICY "Allow read access to owner or guests" ON public.winloss_records FOR SELECT USING ((user_id IS NULL) OR (auth.uid()::text = user_id));
-- CREATE POLICY "Allow insert access to anyone" ON public.winloss_records FOR INSERT WITH CHECK ((user_id IS NULL) OR (auth.uid()::text = user_id));
-- CREATE POLICY "Allow delete access to owners or guests" ON public.winloss_records FOR DELETE USING ((user_id IS NULL) OR (auth.uid()::text = user_id));
-- =========================================================================

-- 1. Create the records table for storing duel achievements and details
CREATE TABLE IF NOT EXISTS public.winloss_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text NOT NULL, -- 'win', 'loss', 'draw' (or 'tie')
    reason text NOT NULL DEFAULT '',
    image_path text NULL, -- uploaded image URL/path
    user_id text NULL, -- stores authenticated user ID or guest ID (allows UUID and non-UUID custom IDs)
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the settings table for global and user-specific configurations
CREATE TABLE IF NOT EXISTS public.winloss_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL DEFAULT 'global', -- 'global' for site-wide defaults, or a User UUID for custom user overrides
    key text NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_winloss_user_settings_key UNIQUE (user_id, key)
);

-- 3. Enable Row Level Security (RLS) on both tables for security (Optional but Recommended)
ALTER TABLE public.winloss_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.winloss_settings ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for the records table
-- Policy: Allow everyone to read guest records (user_id IS NULL), and authenticated users to read their own records
CREATE POLICY "Allow read access to owner or guests" ON public.winloss_records
    FOR SELECT
    USING (
        (user_id IS NULL) OR 
        (auth.uid()::text = user_id)
    );

-- Policy: Allow users to insert records with their own ID, or guests to insert null user_id records
CREATE POLICY "Allow insert access to anyone" ON public.winloss_records
    FOR INSERT
    WITH CHECK (
        (user_id IS NULL) OR 
        (auth.uid()::text = user_id)
    );

-- Policy: Allow owners to delete their own records or anyone to delete guest records
CREATE POLICY "Allow delete access to owners or guests" ON public.winloss_records
    FOR DELETE
    USING (
        (user_id IS NULL) OR 
        (auth.uid()::text = user_id)
    );

-- 5. Create RLS Policies for the settings table
-- Policy: Allow read access to all settings (so users can get 'global' defaults as well as their own custom settings)
CREATE POLICY "Allow select on settings" ON public.winloss_settings
    FOR SELECT
    USING (true);

-- Policy: Allow insertions / updates / deletes for 'global' settings or the user's own setting entries
CREATE POLICY "Allow change on settings for owner or global" ON public.winloss_settings
    FOR ALL
    USING (
        (user_id = 'global') OR 
        (auth.uid()::text = user_id)
    );

-- 6. Seed initial DEFAULT values for the 'global' configuration settings
INSERT INTO public.winloss_settings (user_id, key, value) VALUES
    ('global', 'win_meme_url', '/uploads/win.png'),
    ('global', 'win_meme_quote', '麻了！完全掌握|Dominance established.|さすがですね！'),
    ('global', 'loss_meme_url', '/uploads/loss.png'),
    ('global', 'loss_meme_quote', '大意了，沒有閃|You activated their trap card...|私の...完全なる敗北だ....'),
    ('global', 'draw_meme_url', '/uploads/tie.png'),
    ('global', 'draw_meme_quote', '下次一定|Break even, barely.|奇跡 勝負つかず.....'),
    ('global', 'lang', 'ja'),
    ('global', 'bgm_path', ''),
    ('global', 'win_sound_path', ''),
    ('global', 'loss_sound_path', ''),
    ('global', 'tab_sound_path', ''),
    ('global', 'select_win_sound_path', ''),
    ('global', 'select_loss_sound_path', ''),
    ('global', 'submit_sound_path', '')
ON CONFLICT (user_id, key) DO UPDATE 
SET value = EXCLUDED.value;
