-- 1. Create the records table for storing duel achievements and details
CREATE TABLE IF NOT EXISTS public.records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type text NOT NULL, -- 'win', 'loss', 'draw' (or 'tie')
    reason text NOT NULL DEFAULT '',
    image_path text NULL, -- uploaded image URL/path
    user_id uuid NULL, -- references authenticated auth.users
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the settings table for global and user-specific configurations
CREATE TABLE IF NOT EXISTS public.settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL DEFAULT 'global', -- 'global' for site-wide defaults, or a User UUID for custom user overrides
    key text NOT NULL,
    value text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_key UNIQUE (user_id, key)
);

-- 3. Enable Row Level Security (RLS) on both tables for security (Optional but Recommended)
ALTER TABLE public.records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for the records table
-- Policy: Allow everyone to read guest records (user_id IS NULL), and authenticated users to read their own records
CREATE POLICY "Allow read access to owner or guests" ON public.records
    FOR SELECT
    USING (
        (user_id IS NULL) OR 
        (auth.uid() = user_id)
    );

-- Policy: Allow users to insert records with their own ID, or guests to insert null user_id records
CREATE POLICY "Allow insert access to anyone" ON public.records
    FOR INSERT
    WITH CHECK (
        (user_id IS NULL) OR 
        (auth.uid() = user_id)
    );

-- Policy: Allow owners to delete their own records or anyone to delete guest records
CREATE POLICY "Allow delete access to owners or guests" ON public.records
    FOR DELETE
    USING (
        (user_id IS NULL) OR 
        (auth.uid() = user_id)
    );

-- 5. Create RLS Policies for the settings table
-- Policy: Allow read access to all settings (so users can get 'global' defaults as well as their own custom settings)
CREATE POLICY "Allow select on settings" ON public.settings
    FOR SELECT
    USING (true);

-- Policy: Allow insertions / updates / deletes for 'global' settings or the user's own setting entries
CREATE POLICY "Allow change on settings for owner or global" ON public.settings
    FOR ALL
    USING (
        (user_id = 'global') OR 
        (auth.uid()::text = user_id)
    );

-- 6. Seed initial DEFAULT values for the 'global' configuration settings
INSERT INTO public.settings (user_id, key, value) VALUES
    ('global', 'win_meme_url', '/uploads/rockman_win.png'),
    ('global', 'win_meme_quote', '不愧是你！|Excellent work!|さすがですね！'),
    ('global', 'loss_meme_url', '/uploads/zero_lose.png'),
    ('global', 'loss_meme_quote', '投降輸一半|Mission Failed...|何者なんだ、これ...'),
    ('global', 'draw_meme_url', '/uploads/tie_meme.png'),
    ('global', 'draw_meme_quote', '沒輸沒贏|Double KO!|勝負つかず...'),
    ('global', 'lang', 'ja'),
    ('global', 'bgm_path', ''),
    ('global', 'win_sound_path', ''),
    ('global', 'loss_sound_path', ''),
    ('global', 'tab_sound_path', ''),
    ('global', 'select_win_sound_path', ''),
    ('global', 'select_loss_sound_path', ''),
    ('global', 'submit_sound_path', '')
ON CONFLICT (user_id, key) DO UPDATE 
SET value = EXCLUDED.value;
